#!/bin/bash

# switch or create branch shortcut

repo=$(basename `git rev-parse --show-toplevel`)
branch=$(git symbolic-ref --short HEAD)
echo "Repository: $repo"
echo "Branch: $branch"

if [ "$1" != "" ]; then
    echo "git fetch --all"
    git fetch --all

    exist=`git branch --list $1`
    if [ "$exist" != "" ]; then
        echo "-switch to local branch"
        cmd="git checkout $1"
        echo $cmd && eval $cmd
    else
        exist=`git branch -ar --list origin/$1`
        if [ "$exist" != "" ]; then
            echo "-copy branch from remote server"
            cmd="git checkout -b $1 origin/$1"
            echo $cmd && eval $cmd
        else
            echo "-create nerw local branch"
            cmd="git checkout -b $1 $branch"
            echo $cmd && eval $cmd
        fi
    fi
else
    echo "git branch"
    git branch -ar
    git branch
fi
