#!/bin/bash

# switch or create branch shortcut

repo=$(basename `git rev-parse --show-toplevel`)
branch=$(git symbolic-ref --short HEAD)

br=$1
re='^[0-9]+$'
if [[ "$br" =~ $re ]] ; then
   br=feature-$br
   echo "rename to $br"
fi

if [ "$br" = "list" ]; then
    echo "-switch to local branch"
    cmd="git branch -ar;git branch"
    echo $cmd && eval $cmd
elif [ "$br" != "" ]; then
    echo "git fetch --all"
    git fetch --all

    exist=`git branch --list $br`
    if [ "$exist" != "" ]; then
        echo "-switch to local branch"
        cmd="git checkout $br"
        echo $cmd && eval $cmd
    else
        exist=`git branch -ar --list origin/$br`
        if [ "$exist" != "" ]; then
            echo "-copy branch from remote server"
            cmd="git checkout -b $br origin/$br"
            echo $cmd && eval $cmd
        else
            echo "-create nerw local branch"
            cmd="git checkout -b $br $branch"
            echo $cmd && eval $cmd
        fi
    fi
else
    COLOR "Current branch is <bpurple>$branch</bpurple> in repository <bcyan>$repo</bcyan>"
fi
