#!/bin/bash

# print in color
color="\e[1;33m"
text=$@

function string_replace {
    echo "$1" | sed -r 's:'"$2"':'"$3"':g'
}

collorsArray=(black red green yellow blue purple cyan white)

#Regular
for i in "${!collorsArray[@]}"; do
        item=${collorsArray[$i]}
        text=$(string_replace "$text" "<${item}>" "\\\e[0;3${i}m")
        text=$(string_replace "$text" "</${item}>" "\\\e[0m")
done

#Bold

for i in "${!collorsArray[@]}"; do
        item=${collorsArray[$i]}
        text=$(string_replace "$text" "<b${item}>" "\\\e[1;3${i}m")
        text=$(string_replace "$text" "</b${item}>" "\\\e[0m")
done

#Underline

for i in "${!collorsArray[@]}"; do
        item=${collorsArray[$i]}
        text=$(string_replace "$text" "<u${item}>" "\\\e[4;3${i}m")
        text=$(string_replace "$text" "</u${item}>" "\\\e[0m")
done

#Background

for i in "${!collorsArray[@]}"; do
        item=${collorsArray[$i]}
        text=$(string_replace "$text" "<h${item}>" "\\\e[4${i}m")
        text=$(string_replace "$text" "</h${item}>" "\\\e[0m")
done

echo -e "$text"
