#!/bin/bash

#docker

repo=$(basename `git rev-parse --show-toplevel`)

if [ "$repo" = "feed" ]; then
    cd /var/www/src/app/docker

    if [ "$1" = "status" ]; then
        ./scripts/status.sh
    fi

    if [ "$1" = "clean" ]; then
        ./scripts/clear-containers.sh
    fi

    if [ "$1" = "info" ]; then
        ./scripts/info.sh
    fi

    if [ "$1" = "init" ]; then
        cd /var/www/src/
        rm /var/www/src/app
        ln -s /var/www/src/feed /var/www/src/app
        cd /var/www/src/app/docker
        ./scripts/init.sh
    fi

    if [ "$1" = "start" ]; then
        ./scripts/up.sh
    fi

    if [ "$1" = "stop" ]; then
        ./scripts/stop.sh
    fi

    if [ "$1" = "ssh" ] && [ "$2" != "" ]; then
        ./scripts/ssh.sh $2
    fi

    if [ "$1" = "db" ]; then
        ./scripts/ssh.sh docker_mysql_1
    fi

    if [ "$1" = "console" ]; then
        ./scripts/ssh.sh docker_appphp_1
    fi

    if [ "$1" = "cmd" ]; then
        docker exec docker_appphp_1 app/console $2
    fi

    if [ "$1" = "reindex" ]; then
        docker exec docker_appphp_1 app/console es:reindex 'one-by-one' --force --no-interaction
    fi

    if [ "$1" = "schema" ] && [ "$2" = "update" ]; then
        docker exec docker_appphp_1 app/console doctrine:schema:update --force --dump-sql
    fi

    if [ "$1" = "" ]; then
        COLOR "<green>status</green> <blue>>></blue>"
    fi

fi

if [ "$repo" = "ats" ]; then
    cd /var/www/src/app/docker

    if [ "$1" = "clean" ]; then
        ./scripts/clear-containers.sh
    fi

    if [ "$1" = "status" ]; then
        ./scripts/dev/status.sh
    fi

    if [ "$1" = "info" ]; then
        ./scripts/info.sh
    fi

    if [ "$1" = "init" ]; then
        cd /var/www/src/
        rm /var/www/src/app
        ln -s /var/www/src/ats /var/www/src/app
        cd /var/www/src/app/docker
        pwd
        ./scripts/dev/up.sh
        ./scripts/dev/symfony/init.sh
    fi

    if [ "$1" = "start" ] || [ "$1" = "up" ]; then
        ./scripts/dev/up.sh
    fi

    if [ "$1" = "stop" ]; then
        ./scripts/dev/stop.sh
    fi

    if [ "$1" = "reset" ]; then
        ./scripts/dev/reset.sh
    fi

    if [ "$1" = "ssh" ] && [ "$2" != "" ]; then
        ./scripts/ssh.sh $2
    fi

    if [ "$1" = "db" ]; then
        ./scripts/ssh.sh docker_mysql_1
    fi

    if [ "$1" = "console" ]; then
        ./scripts/ssh.sh docker_appphp_1
    fi

    if [ "$1" = "cmd" ]; then
        docker exec docker_appphp_1 app/console $2
    fi

    if [ "$1" = "reindex" ]; then
        docker exec docker_appphp_1 app/console es:reindex 'one-by-one' --force --no-interaction
    fi

    if [ "$1" = "schema" ] && [ "$2" = "update" ]; then
        docker exec docker_appphp_1 app/console doctrine:schema:update --force --dump-sql
    fi

    if [ "$1" = "" ]; then
        COLOR "<green>clean</green> <blue>>></blue>"
        COLOR "<green>status</green> <blue>>></blue>"
        COLOR "<green>info</green> <blue>>></blue>"
        COLOR "<green>init</green> <blue>>></blue>"
        COLOR "<green>start</green> <blue>>></blue>"
        COLOR "<green>stop</green> <blue>>></blue>"
        COLOR "<green>reset</green> <blue>>></blue>"
        COLOR "<green>ssh</green> <purple>{cmd}</purple> <blue>>></blue>"
        COLOR "<green>db</green> <blue>>></blue>"
        COLOR "<green>console</green> <blue>>></blue>"
        COLOR "<green>cmd</green> <purple>{cmd}</purple> <blue>>></blue>"
        COLOR "<green>reindex</green> <blue>>></blue>"
        COLOR "<green>schema</green> <blue>>></blue>"
    fi

fi
