#!/bin/bash

# repeat comand 
# sudo apt-get install php5-sqlite3

#save last command command
function SV() {
    commandNum=2
    if [ "$2" != "" ] && [[ $2 =~ ^[0-9]+$ ]]; then #get N command; check if is num
        commandNum=$(($2+1))
    fi;

    savedCommand=$(fc -l -${commandNum} | sed -n 1p | cut -c 4-) # | sed -n 1p | cut -c 4-
    
    aliasName=""
    if [ "$1" != "" ]; then
      aliasName="$1"
    fi;

    nowTime=`date +"%Y-%m-%d %H:%M:%S"`
    aliasId=`DB query "select id from cmd where alias = '${aliasName}'" --single`

    if [ "$aliasName" != "" ] && [ "$savedCommand" != "" ]; then
      if [ "$aliasId" = "" ]; then
        echo "cmd insert: $savedCommand"
        echo "alias: $aliasName"
        DB exec "INSERT INTO cmd (alias, cmd, exec_time) VALUES ('${aliasName}', '${savedCommand}', '${nowTime}')"
      else
        echo "cmd update: $savedCommand"
        echo "alias: $aliasName"
        DB exec "UPDATE cmd SET cmd = '${savedCommand}', exec_time = '${nowTime}' WHERE id = '${aliasName}' "
      fi;
    fi;
}

if [ "$1" = "--list" ]; then
    DB query "select * from cmd"
elif [ "$1" = "--load" ]; then
    export -f SV
elif [ "$1" = "--init" ]; then
    echo "create table"
    DB exec "CREATE TABLE IF NOT EXISTS cmd
        (
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
            alias VARCHAR(255) NULL,
            cmd VARCHAR(255) NOT NULL,
            exec_time VARCHAR(20) NOT NULL
        );"
elif [ "$1" = "--remove" ] && [ "$2" != "" ]; then
      removeAlias="$2"
      if [[ $removeAlias =~ ^[0-9]+$ ]]; then #remove with id
        echo "remove id: $removeAlias"
        DB exec "DELETE from cmd WHERE id = '${removeAlias}'"
      else
        echo "remove alias: $removeAlias"
        DB exec "DELETE from cmd WHERE alias = '${removeAlias}'"
      fi;
elif [ "$1" = "--clean-all" ]; then
      echo "Purge cmd table"
      DB exec "DELETE from cmd WHERE 1;"
elif [ "$1" != "" ]; then
    cmd=`DB query "select cmd from cmd where alias = '$1'" --single`
    echo "run: $cmd"
    eval $cmd
elif [ "$1" = "" ]; then
    echo "DO --list           >> list all commands"
    echo "DO --init           >> create table cmd"
    echo ". DO --load         >> load SV function"
    echo "DO {alias}          >> run command"
    echo "SV                  >> insert or update last command"
    echo "SV {alias}          >> save last command with {alias}"
    echo "SV {alias} {n}      >> save last {n} command with {alias}"
    echo "DO --remove {alias} >> remove command with {alias} from db"
    echo "DO --remove {id}    >> remove command with {id} from db"
    echo "DO --clean-all      >> purge database"
fi;
