#!/bin/bash

#docker 

repo=$(basename `git rev-parse --show-toplevel`)

if [ "$repo" = "feed" ]; then
    cd /var/www/src/$repo/docker

    if [ "$1" = "status" ]; then
        ./scripts/status.sh
    fi

    if [ "$1" = "clean" ]; then
        ./scripts/clear-containers.sh
    fi

    if [ "$1" = "info" ]; then
        ./scripts/info.sh
    fi

    if [ "$1" = "init" ]; then
        ./scripts/init.sh
    fi

    if [ "$1" = "start" ]; then
        ./scripts/up.sh
    fi

    if [ "$1" = "stop" ]; then
        ./scripts/stop.sh
    fi

    if [ "$1" = "ssh" ] && [ "$2" != "" ]; then
        ./scripts/ssh.sh $2
    fi

    if [ "$1" = "db" ]; then
        ./scripts/ssh.sh docker_mysql_1
    fi

    if [ "$1" = "console" ]; then
        ./scripts/ssh.sh docker_appphp_1
    fi

    if [ "$1" = "cmd" ]; then
        docker exec docker_appphp_1 app/console $2
    fi

    if [ "$1" = "reindex" ]; then
        docker exec docker_appphp_1 app/console es:reindex 'one-by-one' --force --no-interaction
    fi

    if [ "$1" = "schema" ] && [ "$2" = "update" ]; then
        docker exec docker_appphp_1 app/console doctrine:schema:update --force --dump-sql
    fi

fi
