#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# open file or directory sublime text shortcut

import sys
import os
import re
import fileinput


def touch(path):
    with open(path, 'a'):
        os.utime(path, None)

if len(sys.argv)<=1:
    os.system('nohup thunar . >/dev/null 2>&1 &')
elif len(sys.argv)==2 and sys.argv[1] == '-i':
    for line in fileinput.input():
        if line == 'exit':
           exit(0);
        #print(line)
        #os.system('e '+line)
else:
    matchObj = re.match( r'^([^:]*)(:[0-9]+){0,1}$', sys.argv[1], re.M|re.I)
    if matchObj:
        if os.path.isdir(matchObj.group(1)):
            os.system('nohup thunar "'+sys.argv[1]+'" >/dev/null 2>&1 &')
        else:
            if not os.path.isfile(matchObj.group(1)):
                touch(matchObj.group(1))

            if os.path.isfile(matchObj.group(1)):
                os.system('subl "'+sys.argv[1]+'"')
exit(0);