#!/bin/bash

# grep shortcut

if [ -z "$1" ];
then
    echo "missing argument";
    exit;
fi

if [ "$1" = "url" ]; then

    if [ -z "$2" ];
    then
        pwd=$(pwd)
        enc=$(python -c "import sys, urllib as ul; print ul.quote_plus('$pwd')")
        firefox "http://grep.dev/grep.php?view=search&dir=$enc&file_find=file_find&grep=grep"
    else
        pwd=$(pwd)
        enc=$(python -c "import sys, urllib as ul; print ul.quote_plus('$pwd')")
        param=$(python -c "import sys, urllib as ul; print ul.quote_plus('$2')")
        #firefox "http://grep.dev/grep.php?search=&view=search&replacestring=&dir=$enc&ext_check=&file_find=file_find&grep=grep"
        firefox "http://grep.dev/grep.php?search=$param&view=search&dir=$enc&file_find=file_find&grep=grep"
    fi

elif [ "$1" = "fast" ]; then
    time grep -nri --include='*.css' --include='*.js' --include='*.php' --include='*.xml' --include='*.json' --include='*.htm' --include='*.html' --include='*.twig' --include='*.txt' --include='*.yml' --color=always --exclude-dir="TransferV2" --exclude-dir="cache" --exclude-dir="web" "$2" . | more
elif [ "$1" = "open" ]; then
    files=$(grep -lnri "$2" . 2>/dev/null)
    subl $files
else
    time grep -nri --color=always "$@" . | more
fi
