#! /usr/bin/env python
# -*- coding: utf-8 -*-

# view command output in text editor shortcut
# example of use  ls | I

import sys
import os
import fileinput
import tempfile
import time

import random

alphabet = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
pw_length = 8
mypw = ""

for i in range(pw_length):
    next_index = random.randrange(len(alphabet))
    mypw = mypw + alphabet[next_index]

path = '/home/kerberos/temp/isubl_'+mypw
f = open(path, 'w')
for line in fileinput.input():
    f.write(line.rstrip() + '\n')
f.close()

os.system('subl '+path)
time.sleep( 2 )
os.remove(path)
exit(0);