#!/bin/bash

# switch or create branch shortcut

repo=$(basename `git rev-parse --show-toplevel`)
branch=$(git symbolic-ref --short HEAD)

RED "New files in origin/$branch"
git diff --name-only origin/$branch
RED "Diff"
git diff origin/$branch
