#!/bin/bash

# git pull shortcut

branch=$(git symbolic-ref --short HEAD)
repo=$(basename `git rev-parse --show-toplevel`)
echo "Repository: $repo"
echo "Branch: $branch"

if [ "$1" != "" ]; then
    echo "git pull origin $1"
    git pull origin $1
else
    echo "git pull origin $branch"
    git pull origin $branch
fi
