#!/bin/bash

#git push shortcut

repo=$(basename `git rev-parse --show-toplevel`)
branch=$(git symbolic-ref --short HEAD)

if [ "$branch" = "master" ] && [ "$1" = "" ]; then
    COLOR "<bred>WARNING: branch is set to $branch</bred>"

elif [ "$branch" = "develop" ] && [ "$1" = "" ]; then
    COLOR "<bred>WARNING: branch is set to $branch</bred>"
    
elif [ "$1" = "force" ]; then
    echo push to master
    cmd="git push --force origin $branch"
    echo $cmd && eval $cmd

elif [ "$1" = "master" ]; then
    echo push to master
    cmd="git push origin master"
    echo $cmd && eval $cmd

elif [ "$1" = "develop" ]; then
    echo push to master
    cmd="git push origin develop"
    echo $cmd && eval $cmd

elif [ "$repo" = "commands" ]; then
    if [ "$branch" != "master" ] && [ "$branch" != "develop" ]; then
        cmd="git push origin $branch"
        echo $cmd && eval $cmd
        firefox "https://github.com/pekand/commands/compare/develop...$branch"
    fi;
else
    echo "Repository: $repo"
    echo "Branch: $branch"
fi
