#!/bin/bash
for var in "$@"
do
    if [ "$var" = "-x" ]; then
        set -x
    fi
done


if [ "$1" = "checkout" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
    echo -e "\e[31m Svn checkout  \e[0m"

    $user=""
    if ["$3" != ""]; then
        $user="$3"
    fi

    echo "svn checkout  $1 $2 $user"
    svn checkout $2 $3 $user
fi

if [ "$1" = "commit" ]; then
    echo -e "\e[31m Svn commit  \e[0m"

    DATE=`date +%Y-%m-%d`
    svn add --force .
    svn commit -m "$DATE $2"
fi

if [ "$1" = "update" ]; then
    echo -e "\e[31m Svn update  \e[0m"

    svn update
fi

if [ "$1" = "status" ]; then
    echo -e "\e[31m Svn status  \e[0m"

    svn status
fi

if [ "$1" = "log" ]; then
    echo -e "\e[31m Svn log  \e[0m"

    svn log
fi

if [ "$1" = "" ]; then
    echo "svn checkout {url} {dir} {user}"
    echo "svn commit"
    echo "svn update"
    echo "svn status"
fi
