#!/usr/bin/php
<?php

$host='';
$user='root';
$pass='root';

$db = mysql_connect('localhost',$user,$pass);

$word = '';
if (isset($argv[1]) && ($argv[1]=='db')) {
    print_r(getDatabaseNames($db));
}else if (isset($argv[1]) && !isset($argv[2])) {
    $dbname = $argv[1];
    print_r(getTableNames($db, $dbname, $table));
}else if (isset($argv[1]) && isset($argv[2]) && isset($argv[3])) {
    $dbname = array($argv[1]);
    $table = array();
    if (isset($argv[2]) && $argv[2]!="") {
        $table = explode(",", $argv[2]);
    }

    $columns = array();
    if (isset($argv[3]) && $argv[3]!="") {
        $columns = explode(",", $argv[3]);
    }

    $match = searchfor($db, $dbname, $table, $columns);

    print_r($match);
}else if (isset($argv[1]) && isset($argv[2])) {
    $dbname = array($argv[1]);
    $table = array();
    if (isset($argv[2]) && $argv[2]!="") {
        $table = explode(",", $argv[2]);
    }

    $match = searchfor($db, $dbname, $table);

    print_r($match);

} else {
    echo "T db - list databases".PHP_EOL;
    echo "T {dbname} - list tables".PHP_EOL;
    echo "T {dbname} {tablename} - print table".PHP_EOL;
    echo "T {dbname} {tablename} {column} - print column".PHP_EOL;
    die();
}


function gettables($db, $dbname)
{
    mysql_select_db($dbname, $db);

    $sql = mysql_query("SHOW TABLES;");

    $data = array();

    while ($row = mysql_fetch_assoc($sql))
        $data[] = $row;

    return $data;
}


function getdatabases($db)
{

    $sql = mysql_query("SHOW DATABASES;");

    $data = array();

    while ($row = mysql_fetch_assoc($sql))
        $data[] = $row;

    return $data;
}

function getcolumns($db, $dbname, $dbtable)
{

    $sql = mysql_query("SHOW COLUMNS FROM ".$dbtable.";");

    if (!$sql) {
        echo "Error: e001: Table not exist!\n";die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql))
        $data[] = $row;

    return $data;
}

function searchfor($db, $dbname_select = array(), $table_select = array(), $columns_select = array())
{

    $dbnames = array();
    if(count($dbname_select)==0) {
        $dbnametmp = getdatabases($db); //get all databases

        foreach ($dbnametmp as $dbname)
            $dbnames[] = $dbname['Database'];
    } else {
        $dbnames = $dbname_select;
    }

    $data = array();
    foreach($dbnames as $dbname){
        $ecode = mysql_select_db($dbname, $db);

        if (!$ecode) {
            echo "Error: e002: Database not exist!\n";die;
        }

        $tables = array();
        if(count($table_select)==0) {
            $tabletmp = gettables($db, $dbname); // get all tables in database

            foreach ($tabletmp as $tablex)
                $tables[] = $tablex['Tables_in_'.$dbname];
        } else {
            $tables = $table_select;
        }

        $data = array();
        foreach($tables as $table){
            $columnList = "*";

            if (count($columns_select) > 0){
                $columnList = join(", ", $columns_select);                
            }

            $query = "SELECT ".$columnList." FROM ".$table." WHERE true";

            //print_r($query);

            $sql = mysql_query($query);

            if (!$sql) {
                echo "Error: e003: Column not exist!\n";die;
            }

            while ($sql && $row = mysql_fetch_assoc($sql)) {
                $data[$dbname][$table][] = $row;
            }
        }
    }

    return $data;
}

function getStructure($db, $dbname)
{
    /*SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME ='products';*/

    $sql = mysql_query("
        SELECT *
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = '{$dbname}'
        ORDER BY TABLE_SCHEMA ASC, TABLE_NAME ASC, ORDINAL_POSITION ASC
    ");

    $dbstructure = array();
    if (!$sql) {
        echo "Error: e004: Table not exist!\n";die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row;

        $databasename = $row['TABLE_SCHEMA'];
        $tablename = $row['TABLE_NAME'];
        $columnname = $row['COLUMN_NAME'];

        $dbstructure[$databasename][$tablename][$columnname] = $row;
    }

    return $dbstructure;
}


function getIndexies($db, $dbname)
{
    $sql = mysql_query("
        SELECT
            *
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = '{$dbname}';
    ");

    $dbstructure = array();
    if (!$sql) {
        echo "Error: e005: Table not exist!\n";die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row;

        $databasename = $row['TABLE_SCHEMA'];
        $tablename = $row['TABLE_NAME'];
        $columnname = $row['COLUMN_NAME'];

        $dbstructure[$databasename][$tablename][$columnname] = $row;
    }

    return $dbstructure;
}

function getForeginKey($db, $dbname)
{

    mysql_select_db('information_schema', $db);

    $sql = mysql_query("
        SELECT *
        FROM KEY_COLUMN_USAGE
        WHERE  CONSTRAINT_SCHEMA = '{$dbname}'
    ");

    $dbstructure = array();
    if (!$sql) {
        echo "Error: e006: Table not exist!\n";die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row;

        $databasename = $row['TABLE_SCHEMA'];
        $tablename = $row['TABLE_NAME'];
        $columnname = $row['COLUMN_NAME'];
        $reftablename = $row['REFERENCED_TABLE_NAME'];
        $refcolumnname = $row['REFERENCED_COLUMN_NAME'];

        $dbstructure[$databasename][$tablename][$columnname] = $reftablename.'.'.$refcolumnname;
    }

    return $dbstructure;
}

function ForeginKeyClear($db, $dbname, $fkey)
{

    mysql_select_db('information_schema', $db);

    $sql = mysql_query("
        SELECT *
        FROM KEY_COLUMN_USAGE
        WHERE  CONSTRAINT_SCHEMA = '{$dbname}'
    ");

    $dbstructure = array();
    if (!$sql) {
        echo "Error: e007: Table not exist!\n";die;
    }

    $data = array();

    mysql_select_db($dbname, $db);

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row;

        $databasename = $row['TABLE_SCHEMA'];
        $tablename = $row['TABLE_NAME'];
        $columnname = $row['COLUMN_NAME'];
        $reftablename = $row['REFERENCED_TABLE_NAME'];
        $refcolumnname = $row['REFERENCED_COLUMN_NAME'];

        if ($reftablename.'.'.$refcolumnname == $fkey) {
            echo "Clear: ".$tablename.".".$columnname."\n";
            $query = "UPDATE `".$tablename."` SET `".$columnname."`=NULL WHERE true;";
            $res = mysql_query($query, $db);
            if (!$res) {
                echo 'Error: e008: '.mysql_error($db);die;
            }
        }

    }

    return $dbstructure;
}

function getTableNames($db, $dbname)
{
    mysql_select_db($dbname, $db);

    $sql = mysql_query("SHOW TABLES FROM {$dbname}", $db);
    if (!$sql) {
        echo 'Error: e009: '.mysql_error($db);die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row['Tables_in_'.$dbname];
    }

    return $data;
}

function getDatabaseNames($db)
{

    $sql = mysql_query("SHOW DATABASES", $db);
    if (!$sql) {
        echo 'Error: e010: '.mysql_error($db);die;
    }

    $data = array();

    while ($row = mysql_fetch_assoc($sql)) {
        $data[] = $row['Database'];
    }

    return $data;
}
