#!/usr/bin/env python3
import sys

a = ""
if len(sys.argv) > 0:
  a=sys.argv[1]

if a == "x":
	print("1")

if a == "w":
	print("2")

if a == "wx" or a == "xw":
	print("3")

if a == "r":
	print("4")

if a == "rx" or a == "xr":
	print("5")

if a == "rw" or a == "wr":
	print("6")

if a == "rwx" or a == "rxw" or a == "wrx" or a == "wxr"  or a == "xrw" or a == "xwr":
	print("7")

def conv(a):
	if a == 1:
		return("x")

	if a == 2:
		return("w")

	if a == 3:
		return("wx")

	if a == 4:
		return("r")

	if a == 5:
		return("rx")

	if a == 6:
		return("rw")

	if a == 7:
		return("rwx")

	return "?"


try:
    a = int(a)
except ValueError:
    exit()


if a>=1 and a <=7:
	print(conv(a))

if a>=111 and a <=777:
	d1 = a % 10
	a = a // 10
	d2 = a % 10
	a = a // 10
	d3 = a % 10		
	print("u:"+conv(d3)+"|"+"o:"+conv(d2)+"|"+"g:"+conv(d1))




